type Query {
  getHistory(accessToken: String!): History

  getAllMemembers: [Member!]!

#  Relacionados a pagos en socios
  getFinesById(accessToken: String!): [Fine!]!

  getUsersPayments(accessToken: String!): [UserPayment!]!
}

# General
type Member {
  userId: String!
  name: String!
}

# Socios - Historial
type History {
  owedCapital: Float
  payedToCapital: Float
}

# Socios - Pagos -------
# Formulario de Pagos
type UserPayment {
  commentary: String!
  paymentDate: String!
  paymentId: String!
  state: String!
  ticketNum: String!
  totalAmount: Float!
  photo: String!
}

type Fine {
  reason: String!
  quantity: Float!
}
