type Query {
  getHistory(accessToken: String!): History

  getAllMembers: [Member!]!

#  Relacionados a pagos en socios
  getFinesById(accessToken: String!): [Fine!]!

  getUsersPayments(accessToken: String!): [UserPayment!]!

  getPendingLoansQuotas(accessToken: String!): [LoanQuota!]!

  getMonthlyAffiliateQuota(accessToken: String!): [MonthlyQuota!]!
}

# General
type Member {
  userId: String!
  name: String!
}

# Socios - Historial
type History {
  owedCapital: Float
  payedToCapital: Float
}

# Socios - Pagos -------
# Formulario de Pagos
enum PaymentStatus {
  ON_REVISION
  REJECTED
  ACCEPTED
}

type UserPayment {
  id: String!
  name: String!
  commentary: String
  paymentDate: String!
  state: PaymentStatus!
  ticketNum: String!
  photo: String!
  totalAmount: Float!
  accountNum: String!
}

type Fine {
  reason: String!
  quantity: Float!
}

type LoanQuota {
  userId: String!
  monto: Float!
  fechaVencimiento: String!
  montoPagado: Float!
  multa: Float!
  pagadaPor: String
  tipo: String!
  loanId: String!
  pagada: Boolean!
  numeroQuota: Int!
  nombrePrestamo: String
}

type MonthlyQuota {
  identifier: String!
  userId: String!
  monto: Float!
  nombre: String!
  fechaVencimiento: String!
  extraordinaria: Boolean!
}